module.exports = {
  ['patient-portal.LandingPage']: './src/patient-portal/LandingPage.jsx',
  ['patient-portal.index']: './src/patient-portal/index.jsx',
  ['patient-portal.unsubscribe']: './src/patient-portal/unsubscribe.jsx',
  ['patient-portal.ToULink']: './src/patient-portal/ToULink.jsx',
  ['patient-portal.UnsubscribeLink']: './src/patient-portal/UnsubscribeLink.jsx',
  ['patient-portal.ClinicForms']: { 'dependOn': ['cards-dataentry.LiveTable'], 'import': './src/patient-portal/ClinicForms.jsx' },
  ['patient-portal.ClinicVisits']: { 'dependOn': ['cards-dataentry.LiveTable'], 'import': './src/patient-portal/ClinicVisits.jsx' },
  ['patient-portal.ClinicDashboard']: { 'dependOn': ['cards-dataentry.Questionnaires', 'patient-portal.ClinicForms', 'patient-portal.ClinicVisits'], 'import': './src/patient-portal/ClinicDashboard.jsx' },
  ['patient-portal.clinicIcon']: '@mui/icons-material/Event',
  ['patient-portal.Clinics']: { 'dependOn': ['cards-dataentry.Questionnaires'], 'import': './src/patient-portal/Clinics.jsx' },
  ['patient-portal.PrintHeader']: './src/patient-portal/PrintHeader.jsx',
  ['patient-portal.PatientAccessConfiguration']: { 'dependOn': ['cards-login.loginDialogue'], 'import': './src/patient-portal/PatientAccessConfiguration.jsx' },
  ['patient-portal.PatientAccessConfigurationIcon']: '@mui/icons-material/MedicalInformation',
  ['patient-portal.ToUConfiguration']: { 'dependOn': ['cards-login.loginDialogue'], 'import': './src/patient-portal/ToUConfiguration.jsx' },
  ['patient-portal.ToUConfigurationIcon']: '@mui/icons-material/Handshake',
  ['patient-portal.SurveyInstructionsConfiguration']: { 'dependOn': ['cards-login.loginDialogue'], 'import': './src/patient-portal/SurveyInstructionsConfiguration.jsx' },
  ['patient-portal.SurveyInstructionsConfigurationIcon']: '@mui/icons-material/Quiz',
  ['patient-portal.DashboardSettingsConfiguration']: { 'dependOn': ['cards-login.loginDialogue'], 'import': './src/patient-portal/DashboardSettingsConfiguration.jsx' },
  ['patient-portal.DashboardSettingsConfigurationIcon']: '@mui/icons-material/Dashboard'
};
