[ignore]
glob = [
  "aggregated-frontend/node_modules/**"
]

[pr_reviewer]
enable_review_labels_security = true
enable_review_labels_effort = true
extra_instructions = """
Do not use too formal language, write simple straight to the point review.
Report spelling errors

App stack:
- The backend is built on Apache Sling 11
- The frontend is on React 18 and MUI 5
- The frontend does not use TypeScript

Frontend React Code Style:
- Focus on ensuring the code is well-structured, readable, optimal and adheres to React best practices
- Frontend components has to be functional, not Class components
- Avoiding State Updates in Loops and useEffect() hooks
- Descriptive Naming: variables, functions, and components have to be named clearly and descriptively. Functions should have an action in their name for clarity, e.g. fetchQuestionnaire
- Default properties should not be explicitly set for components
- If the component has a propTypes specified, ensure there is an explicit prop type check is at the very beginning of the component
- The default props has to be specified at the beginning of the component in the props specification

Frontend React Code Formatting:
- Each statement has to be separated by a semicolon (;)
- White Spacing: ensure use of double space indentation

Frontend React CSS Styling:
- Watch use of theme.palette for colors
- define spacing via theme.spacing

"""

[pr_description]
generate_ai_title = true
extra_instructions = """

#### Description of changes

Briefly describe what changes were made, why they are needed, and whether there are any backward compatibility issues.

Emphasize changes related to security, optimisation, refactoring, version upgrade.
"""

[similar_code]
enabled = true
min_lines = 3
number_of_keywords = 7

[checks]
enable_auto_checks_feedback = true

[config]
model = "o3-mini"
fallback_models = ["gpt-4o-2024-11-20"]
git_provider = "github"
publish_output = true
publish_output_progress = true
publish_output_no_suggestions = true
verbosity_level = 0
use_extra_bad_extensions = false
use_wiki_settings_file = true
use_repo_settings_file = true
use_global_settings_file = true
disable_auto_feedback = false
ai_timeout = 120
skip_keys = []
custom_reasoning_model = false
max_description_tokens = 500
max_commits_tokens = 500
max_model_tokens = 32000
custom_model_max_tokens = -1
patch_extension_skip_types = [".md", ".txt"]
allow_dynamic_context = true
max_extra_lines_before_dynamic_context = 8
patch_extra_lines_before = 3
patch_extra_lines_after = 1
secret_provider = ""
cli_mode = false
ai_disclaimer_title = ""
ai_disclaimer = ""
output_relevant_configurations = false
large_patch_policy = "clip"
duplicate_prompt_examples = false
seed = -1
temperature = 0.2
ignore_pr_title = ["^\\[Auto\\]", "^Auto"]
ignore_pr_target_branches = []
ignore_pr_source_branches = []
ignore_pr_labels = []
ignore_pr_authors = []
is_auto_command = false
enable_ai_metadata = false
reasoning_effort = "medium"
enable_auto_approval = false
auto_approve_for_low_review_effort = -1
auto_approve_for_no_suggestions = false
enable_claude_extended_thinking = false
extended_thinking_budget_tokens = 2048
extended_thinking_max_output_tokens = 4096