<?xml version="1.0" encoding="UTF-8"?>
<!--
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
-->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.uhndata.cards</groupId>
    <artifactId>cards-parent</artifactId>
    <version>0.9.41-SNAPSHOT</version>
  </parent>

  <artifactId>cards-integration-tests</artifactId>
  <name>CARDS integration tests</name>
  <description>Tests on the full CARDS distribution.</description>

  <properties>
    <test.host>localhost</test.host>
    <!-- If set to "true" this will start the launchpad with standard debug options, or set to a string to provide custom debug settings -->
    <launchpad.debug/>
  </properties>

  <build>
    <plugins>
      <!-- Reserve the port numbers used by the webapp during the build -->
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <executions>
          <execution>
            <id>reserve-network-port</id>
            <goals>
              <goal>reserve-network-port</goal>
            </goals>
            <phase>process-resources</phase>
            <configuration>
              <minPortNumber>8080</minPortNumber>
              <portNames>
                <portName>http.port</portName>
              </portNames>
            </configuration>
          </execution>
        </executions>
      </plugin>

      <!-- launch the Sling instances to test -->
      <plugin>
        <groupId>org.apache.sling</groupId>
        <artifactId>feature-launcher-maven-plugin</artifactId>
        <version>1.0.4</version>
        <configuration>
          <launches>
            <launch>
              <id>sling-starter-oak-tar</id>
              <feature>
                <groupId>${project.groupId}</groupId>
                <artifactId>cards</artifactId>
                <version>${project.version}</version>
                <classifier>core_tar</classifier>
                <type>slingosgifeature</type>
              </feature>
              <launcherArguments>
                <frameworkProperties>
                  <org.osgi.service.http.port>${http.port}</org.osgi.service.http.port>
                  <org.apache.felix.http.jetty.responseBufferSize>5000000</org.apache.felix.http.jetty.responseBufferSize>
                </frameworkProperties>
              </launcherArguments>
              <startTimeoutSeconds>60</startTimeoutSeconds>
            </launch>
          </launches>
        </configuration>
        <executions>
          <execution>
            <goals>
              <goal>start</goal>
              <goal>stop</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <!-- This is a plugin designed to run integration tests (Surefire is more for unit tests) -->
      <plugin>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>3.5.6</version>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
          </execution>
        </executions>
        <configuration>
          <systemPropertyVariables>
            <launchpad.http.server.url>http://${test.host}:${http.port}/</launchpad.http.server.url>
          </systemPropertyVariables>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <!-- Dependencies needed to compile the test classes -->
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.sling</groupId>
      <artifactId>org.apache.sling.testing.rules</artifactId>
      <version>2.0.2</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.sling</groupId>
      <artifactId>org.apache.sling.testing.clients</artifactId>
      <version>3.1.0</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.apache.httpcomponents</groupId>
      <artifactId>httpcore</artifactId>
      <version>4.4.16</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</project>
