name: 'Install CI Dependencies'
description: 'Installs the Ubuntu packages needed for performing CI'
runs:
  using: "composite"
  steps:
    - name: Update APT package cache
      run: |
        echo "::group::Update APT package cache"
        sudo apt-get update
        echo "::endgroup::"
      shell: bash
    - name: Install openjdk-11-jre
      run: |
        echo "::group::Install openjdk-11-jre"
        sudo apt-get -y install openjdk-11-jre
        echo "::endgroup::"
      shell: bash
    - name: Install maven
      run: |
        echo "::group::Install maven"
        sudo apt-get -y install maven
        echo "::endgroup::"
      shell: bash
    - name: Install python3
      run: |
        echo "::group::Install python3"
        sudo apt-get -y install python3
        echo "::endgroup::"
      shell: bash
    - name: Install Python Modules
      run: |
        echo "::group::Install Python Modules"
        sudo apt-get -y install python3-psutil python3-openssl python3-yaml python3-tzlocal
        echo "::endgroup::"
      shell: bash
    - name: Install curl
      run: |
        echo "::group::Install curl"
        sudo apt-get -y install curl
        echo "::endgroup::"
      shell: bash
