-- Remove the table if it already exists
DROP TABLE CL_EP_IP_EMAIL_CONSENT_IN_LAST_7_DAYS;

-- Create the schema
CREATE TABLE CL_EP_IP_EMAIL_CONSENT_IN_LAST_7_DAYS (
    PAT_MRN varchar(102) NULL,
    EMAIL_ADDRESS varchar(255) NULL,
    ENTRY_TIME datetime2 NULL,
    DISCH_DEPT_NAME varchar(254) NULL,
    EMAIL_CONSENT_YN varchar(3),
    LoadTime datetime2 NULL
);

-- Insert test data
INSERT INTO CL_EP_IP_EMAIL_CONSENT_IN_LAST_7_DAYS
    (PAT_MRN, EMAIL_ADDRESS, ENTRY_TIME, DISCH_DEPT_NAME, EMAIL_CONSENT_YN, LoadTime)
    VALUES
    (1234567, 'test@test.com', '2022-09-21T11:16:20.136Z', 'TG-EMERGENCY', 'Yes', CAST(GETDATE() AS DATE));

INSERT INTO CL_EP_IP_EMAIL_CONSENT_IN_LAST_7_DAYS
    (PAT_MRN, EMAIL_ADDRESS, ENTRY_TIME, DISCH_DEPT_NAME, EMAIL_CONSENT_YN, LoadTime)
    VALUES
    (1234568, 'test2@test.com', '2022-09-21T11:16:20.136Z', 'TG-EMERGENCY', 'No', CAST(GETDATE() AS DATE))

INSERT INTO CL_EP_IP_EMAIL_CONSENT_IN_LAST_7_DAYS
    (PAT_MRN, EMAIL_ADDRESS, ENTRY_TIME, DISCH_DEPT_NAME, EMAIL_CONSENT_YN, LoadTime)
    VALUES
    (1234568, 'test@test.com', '2022-09-21T11:16:20.136Z', 'TW-EMERGENCY', 'No', CAST(GETDATE() AS DATE))
