/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package io.uhndata.cards;

import javax.jcr.ItemNotFoundException;
import javax.jcr.Node;
import javax.jcr.Property;
import javax.jcr.RepositoryException;
import javax.jcr.Session;

import org.apache.sling.api.SlingJakartaHttpServletRequest;
import org.apache.sling.api.resource.Resource;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.mockito.Mockito;

/**
 * Unit tests for the queries generated by {@link PaginationServlet}, focusing on the questionnaire that answer filters
 * imply for the forms being looked at.
 *
 * @version $Id$
 */
public class PaginationServletTest
{
    private static final String FORMS_PATH = "/Forms";

    private static final String SUBJECTS_PATH = "/Subjects";

    private static final String FORMS_TYPE = "cards/FormsHomepage";

    private static final String SUBJECTS_TYPE = "cards/SubjectsHomepage";

    private static final String QUESTIONNAIRE = "e6b97318-f464-4bb2-82e8-b13df62d33f3";

    private static final String OTHER_QUESTIONNAIRE = "b5a6163e-db5a-4deb-822e-5dbe57031627";

    private static final String QUESTION = "0f0e2b91-5b9b-4a71-a0e2-40b0dbd1e5ab";

    private static final String OTHER_QUESTION = "8fc0b7ff-2ba0-4b04-a1c2-5b8ab7fe57ef";

    private static final String SELECT_FORMS = "select distinct n.[jcr:uuid] from [cards:Form] as n";

    private static final String SELECT_SUBJECTS = "select distinct n.[jcr:uuid] from [cards:Subject] as n";

    private static final String COMPLETE_FORMS = " and not n.'statusFlags'='INCOMPLETE'";

    private static final String ORDER = " order by n.'jcr:created' ASC option(index tag cards)";

    private static final String TEXT = "text";

    private static final String EQUALS = "=";

    private PaginationServlet servlet;

    private Session session;

    @Before
    public void setUp()
    {
        this.servlet = new PaginationServlet();
        this.session = Mockito.mock(Session.class);
    }

    @Test
    public void answerFilterRestrictsTheQuestionnaireOfTheForms() throws RepositoryException
    {
        mockQuestion(QUESTION, QUESTIONNAIRE);
        final SlingJakartaHttpServletRequest request = mockRequest(FORMS_PATH, FORMS_TYPE);
        mockAnswerFilters(request, new String[] { QUESTION }, new String[] { "abc" }, new String[] { TEXT },
            new String[] { EQUALS });

        Assert.assertEquals(SELECT_FORMS
            + " inner join [cards:TextAnswer] as childf1_1 on childf1_1.form = n.[jcr:uuid]"
            + " where isdescendantnode(n, '" + FORMS_PATH + "')"
            + " and n.'questionnaire'='" + QUESTIONNAIRE + "'"
            + COMPLETE_FORMS
            + " and childf1_1.'question'='" + QUESTION + "'"
            + " and childf1_1.'value'='abc'"
            + ORDER,
            buildQuery(request));
    }

    @Test
    public void answerFilterRestrictsTheQuestionnaireOfTheJoinedFormsWhenListingSubjects() throws RepositoryException
    {
        mockQuestion(QUESTION, QUESTIONNAIRE);
        final SlingJakartaHttpServletRequest request = mockRequest(SUBJECTS_PATH, SUBJECTS_TYPE);
        mockAnswerFilters(request, new String[] { QUESTION }, new String[] { "abc" }, new String[] { TEXT },
            new String[] { EQUALS });

        Assert.assertEquals(SELECT_SUBJECTS
            + " inner join [cards:Form] as f1 on n.[jcr:uuid] = f1.relatedSubjects"
            + " inner join [cards:TextAnswer] as childf1_1 on f1.[jcr:uuid] = childf1_1.form"
            + " where isdescendantnode(n, '" + SUBJECTS_PATH + "')"
            + " and f1.'questionnaire'='" + QUESTIONNAIRE + "'"
            + " and childf1_1.'question'='" + QUESTION + "'"
            + " and childf1_1.'value'='abc'"
            + ORDER,
            buildQuery(request));
    }

    @Test
    public void valuelessAnswerFilterRestrictsTheQuestionnaireOfTheForms() throws RepositoryException
    {
        mockQuestion(QUESTION, QUESTIONNAIRE);
        final SlingJakartaHttpServletRequest request = mockRequest(FORMS_PATH, FORMS_TYPE);
        Mockito.when(request.getParameterValues("filternotempty")).thenReturn(new String[] { QUESTION });

        Assert.assertEquals(SELECT_FORMS
            + " inner join [cards:TextAnswer] as notemptyf1_1 on notemptyf1_1.form = n.[jcr:uuid]"
            + " where isdescendantnode(n, '" + FORMS_PATH + "')"
            + " and n.'questionnaire'='" + QUESTIONNAIRE + "'"
            + COMPLETE_FORMS
            + " and notemptyf1_1.'question'='" + QUESTION + "'"
            + " and notemptyf1_1.'value' IS NOT NULL"
            + ORDER,
            buildQuery(request));
    }

    @Test
    public void answerFiltersFromDifferentQuestionnairesRestrictEachFormSource() throws RepositoryException
    {
        mockQuestion(QUESTION, QUESTIONNAIRE);
        mockQuestion(OTHER_QUESTION, OTHER_QUESTIONNAIRE);
        final SlingJakartaHttpServletRequest request = mockRequest(SUBJECTS_PATH, SUBJECTS_TYPE);
        mockAnswerFilters(request, new String[] { QUESTION, OTHER_QUESTION }, new String[] { "abc", "def" },
            new String[] { TEXT, TEXT }, new String[] { EQUALS, EQUALS });

        Assert.assertEquals(SELECT_SUBJECTS
            + " inner join [cards:Form] as f1 on n.[jcr:uuid] = f1.relatedSubjects"
            + " inner join [cards:TextAnswer] as childf1_1 on f1.[jcr:uuid] = childf1_1.form"
            + " inner join [cards:Form] as f2 on n.[jcr:uuid] = f2.relatedSubjects"
            + " inner join [cards:TextAnswer] as childf2_1 on f2.[jcr:uuid] = childf2_1.form"
            + " where isdescendantnode(n, '" + SUBJECTS_PATH + "')"
            + " and f1.'questionnaire'='" + QUESTIONNAIRE + "'"
            + " and f2.'questionnaire'='" + OTHER_QUESTIONNAIRE + "'"
            + " and childf1_1.'question'='" + QUESTION + "'"
            + " and childf1_1.'value'='abc'"
            + " and childf2_1.'question'='" + OTHER_QUESTION + "'"
            + " and childf2_1.'value'='def'"
            + ORDER,
            buildQuery(request));
    }

    @Test
    public void filtersOfDifferentTypesOnTheSameQuestionnaireShareOneRestriction() throws RepositoryException
    {
        mockQuestion(QUESTION, QUESTIONNAIRE);
        mockQuestion(OTHER_QUESTION, QUESTIONNAIRE);
        final SlingJakartaHttpServletRequest request = mockRequest(FORMS_PATH, FORMS_TYPE);
        mockAnswerFilters(request, new String[] { QUESTION }, new String[] { "abc" }, new String[] { TEXT },
            new String[] { EQUALS });
        Mockito.when(request.getParameterValues("filterempty")).thenReturn(new String[] { OTHER_QUESTION });

        final String query = buildQuery(request);
        Assert.assertEquals(SELECT_FORMS
            + " inner join [cards:TextAnswer] as childf1_1 on childf1_1.form = n.[jcr:uuid]"
            + " inner join [cards:TextAnswer] as emptyf1_2 on emptyf1_2.form = n.[jcr:uuid]"
            + " where isdescendantnode(n, '" + FORMS_PATH + "')"
            + " and n.'questionnaire'='" + QUESTIONNAIRE + "'"
            + COMPLETE_FORMS
            + " and childf1_1.'question'='" + QUESTION + "'"
            + " and childf1_1.'value'='abc'"
            + " and emptyf1_2.'question'='" + OTHER_QUESTION + "'"
            + " and emptyf1_2.'value' IS NULL"
            + ORDER,
            query);
        Assert.assertEquals(1, countOccurrences(query, "'questionnaire'="));
    }

    @Test
    public void explicitQuestionnaireFilterIsNotRepeated() throws RepositoryException
    {
        mockQuestion(QUESTION, QUESTIONNAIRE);
        final SlingJakartaHttpServletRequest request = mockRequest(FORMS_PATH, FORMS_TYPE);
        mockAnswerFilters(request, new String[] { "cards:Questionnaire", QUESTION },
            new String[] { QUESTIONNAIRE, "abc" }, new String[] { "", TEXT }, new String[] { EQUALS, EQUALS });

        final String query = buildQuery(request);
        Assert.assertEquals(SELECT_FORMS
            + " inner join [cards:TextAnswer] as childf1_1 on childf1_1.form = n.[jcr:uuid]"
            + " where isdescendantnode(n, '" + FORMS_PATH + "')"
            + COMPLETE_FORMS
            + " and n.'questionnaire'='" + QUESTIONNAIRE + "'"
            + " and childf1_1.'question'='" + QUESTION + "'"
            + " and childf1_1.'value'='abc'"
            + ORDER,
            query);
        Assert.assertEquals(1, countOccurrences(query, "'questionnaire'="));
    }

    @Test
    public void negatedQuestionnaireFilterIsStillRestrictedByTheAnswerFilter() throws RepositoryException
    {
        mockQuestion(QUESTION, QUESTIONNAIRE);
        final SlingJakartaHttpServletRequest request = mockRequest(FORMS_PATH, FORMS_TYPE);
        mockAnswerFilters(request, new String[] { "cards:Questionnaire", QUESTION },
            new String[] { OTHER_QUESTIONNAIRE, "abc" }, new String[] { "", TEXT }, new String[] { "<>", EQUALS });

        final String query = buildQuery(request);
        Assert.assertTrue(query.contains(" and n.'questionnaire'='" + QUESTIONNAIRE + "'"));
        Assert.assertTrue(query.contains(" and n.'questionnaire'<>'" + OTHER_QUESTIONNAIRE + "'"));
    }

    @Test
    public void questionnaireFilterAloneAddsNoExtraRestriction() throws RepositoryException
    {
        final SlingJakartaHttpServletRequest request = mockRequest(FORMS_PATH, FORMS_TYPE);
        mockAnswerFilters(request, new String[] { "cards:Questionnaire" }, new String[] { QUESTIONNAIRE },
            new String[] { "" }, new String[] { EQUALS });

        Assert.assertEquals(SELECT_FORMS
            + " where isdescendantnode(n, '" + FORMS_PATH + "')"
            + COMPLETE_FORMS
            + " and n.'questionnaire'='" + QUESTIONNAIRE + "'"
            + ORDER,
            buildQuery(request));
    }

    @Test
    public void metadataFilterAddsNoQuestionnaireRestriction() throws RepositoryException
    {
        final SlingJakartaHttpServletRequest request = mockRequest(FORMS_PATH, FORMS_TYPE);
        mockAnswerFilters(request, new String[] { "cards:CreatedBy" }, new String[] { "admin" },
            new String[] { "" }, new String[] { EQUALS });

        Assert.assertEquals(SELECT_FORMS
            + " where isdescendantnode(n, '" + FORMS_PATH + "')"
            + COMPLETE_FORMS
            + " and n.'jcr:createdBy'='admin'"
            + ORDER,
            buildQuery(request));
    }

    @Test
    public void unknownQuestionAddsNoQuestionnaireRestriction() throws RepositoryException
    {
        Mockito.when(this.session.getNodeByIdentifier(QUESTION)).thenThrow(new ItemNotFoundException());
        final SlingJakartaHttpServletRequest request = mockRequest(FORMS_PATH, FORMS_TYPE);
        mockAnswerFilters(request, new String[] { QUESTION }, new String[] { "abc" }, new String[] { TEXT },
            new String[] { EQUALS });

        Assert.assertFalse(buildQuery(request).contains("'questionnaire'"));
    }

    private String buildQuery(final SlingJakartaHttpServletRequest request) throws RepositoryException
    {
        return this.servlet.createQuery(request, this.session, this.servlet.parseFiltersFromRequest(request));
    }

    private SlingJakartaHttpServletRequest mockRequest(final String path, final String resourceType)
        throws RepositoryException
    {
        final Node homepage = Mockito.mock(Node.class);
        Mockito.when(homepage.hasProperty("childNodeType")).thenReturn(false);

        final Resource resource = Mockito.mock(Resource.class);
        Mockito.when(resource.getPath()).thenReturn(path);
        Mockito.when(resource.getResourceType()).thenReturn(resourceType);
        Mockito.when(resource.adaptTo(Node.class)).thenReturn(homepage);

        final SlingJakartaHttpServletRequest request = Mockito.mock(SlingJakartaHttpServletRequest.class);
        Mockito.when(request.getResource()).thenReturn(resource);
        return request;
    }

    private void mockAnswerFilters(final SlingJakartaHttpServletRequest request, final String[] names,
        final String[] values, final String[] types, final String[] comparators)
    {
        Mockito.when(request.getParameterValues("filternames")).thenReturn(names);
        Mockito.when(request.getParameterValues("filtervalues")).thenReturn(values);
        Mockito.when(request.getParameterValues("filtertypes")).thenReturn(types);
        Mockito.when(request.getParameterValues("filtercomparators")).thenReturn(comparators);
    }

    private void mockQuestion(final String question, final String questionnaire) throws RepositoryException
    {
        final Property questionnaireUuid = Mockito.mock(Property.class);
        Mockito.when(questionnaireUuid.getString()).thenReturn(questionnaire);
        final Node questionnaireNode = Mockito.mock(Node.class);
        Mockito.when(questionnaireNode.isNodeType("cards:Questionnaire")).thenReturn(true);
        Mockito.when(questionnaireNode.getProperty("jcr:uuid")).thenReturn(questionnaireUuid);

        final Node sectionNode = Mockito.mock(Node.class);
        Mockito.when(sectionNode.getParent()).thenReturn(questionnaireNode);

        final Property dataType = Mockito.mock(Property.class);
        Mockito.when(dataType.getString()).thenReturn(TEXT);
        final Node questionNode = Mockito.mock(Node.class);
        Mockito.when(questionNode.getParent()).thenReturn(sectionNode);
        Mockito.when(questionNode.getProperty("dataType")).thenReturn(dataType);

        Mockito.when(this.session.getNodeByIdentifier(question)).thenReturn(questionNode);
    }

    private static int countOccurrences(final String haystack, final String needle)
    {
        int count = 0;
        int index = haystack.indexOf(needle);
        while (index >= 0) {
            ++count;
            index = haystack.indexOf(needle, index + needle.length());
        }
        return count;
    }
}
